name: Refresh Bundled Files
on:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: mstksg/get-package@v1
        with:
                apt-get: wget libxml2-utils
      - name: Refresh Bundled Files
        run: |
          make ci-update-bundled-deps
      - name: Push to master
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
